name = "EquilibriumMeasures"
uuid = "f387465c-e20c-5ab1-9210-5d86af51062a"
version = "0.1.0"

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
ContinuumArrays = "7ae1f121-cc2c-504b-ac30-9b923412ae5c"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FastTransformsForwardDiff = "77fa7db0-1c81-401d-9fde-3592fc42b8bc"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
InfiniteLinearAlgebra = "cde9dba0-b1de-11e9-2c62-0bab9446c55c"
Infinities = "e1ba4f0e-776d-440f-acd9-e1d2e9742647"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LazyBandedMatrices = "d7e5e226-e90b-4449-9968-0f923699bf6f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixFactorizations = "a3b82374-2e81-5b9e-98ce-41277c0e4c87"
SingularIntegrals = "d7440221-8b5e-42fc-909c-0567823f424a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BandedMatrices = "0.17"
BlockArrays = "0.16.6"
ClassicalOrthogonalPolynomials = "0.8, 0.9, 0.10, 0.11"
ContinuumArrays = "0.12, 0.13, 0.14"
DomainSets = "0.5, 0.6"
FastTransformsForwardDiff = "0.0.2"
FillArrays = "1"
ForwardDiff = "0.10.6"
InfiniteArrays = "0.12"
InfiniteLinearAlgebra = "0.6"
Infinities = "0.1"
IntervalSets = "0.5, 0.6, 0.7"
LazyArrays = "1"
LazyBandedMatrices = "0.8"
MatrixFactorizations = "1, 2"
SingularIntegrals = "0.0.1, 0.0.2, 0.0.3, 0.1, 0.2"
StaticArrays = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
